name: Build and Run in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Project in Docker
        run: |
          echo "processor    : 0" > /tmp/mock_cpuinfo
          echo "model name   : ARMv7 Processor rev 4 (v7l)" >> /tmp/mock_cpuinfo
          echo "Hardware     : BCM2835" >> /tmp/mock_cpuinfo
          echo "Revision     : 9000c1" >> /tmp/mock_cpuinfo
          echo "Serial       : 0000000000000000" >> /tmp/mock_cpuinfo
          docker run --rm --platform linux/arm/v7 \
            -v $(pwd):/project \
            -w /project \
            balenalib/rpi-debian:bookworm \
            bash -c "
              set -e
              apt-get update &&
              apt-get install -y build-essential gcc g++ cmake git wget &&
              
              git clone https://github.com/Gaucho-Rocket-Project/WiringPi.git
              cd WiringPi
              
              # build the package
              ./build debian
              mv debian-template/wiringpi-3.0-1.deb .
              
              # install it
              sudo apt install ./wiringpi-3.0-1.deb
              
              cd /project &&
              mkdir -p build &&
              cd build &&
              cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ &&
              make &&
              ./main
            "

