name: Build and Run in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Project in Docker
        run: |
          docker run --rm --platform linux/arm/v7 \
            -v $(pwd):/project \
            -w /project \
            balenalib/rpi-debian:bullseye \
            bash -c "
              set -e
              apt-get update &&
              apt-get install -y build-essential gcc g++ cmake git wget &&
              git clone https://github.com/WiringPi/WiringPi.git
              cd WiringPi
              ./build debian
              mv debian-template/wiringpi-3.0-1.deb .
              # install it
              sudo apt install ./wiringpi-3.0-1.deb
              sed -i 's/sudo //g' build &&  # Remove sudo from build script
              sed -i '/uninstall/d' build &&  # Remove uninstall command
              ./build &&
              cp -r /tmp/WiringPi /usr/local/include &&
              cd /project &&
              mkdir -p build &&
              cd build &&
              cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ &&
              make &&
              ./main
            "
